<a href="https://colab.research.google.com/github/Lalasa-web/Gen-AI-with-prompt-engineering-/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([10, 20, 30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s.name = "calories"
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.index #start = include, end = exclude, step = values to jump

RangeIndex(start=0, stop=5, step=1)

In [ ]:
#indexing
s[0]

np.int64(10)

In [ ]:
s[0:2]

0    10
1    20
Name: calories, dtype: int64

In [ ]:
#iloc -> location based indexing (starting : included, stopping : excluded)
s.iloc[3]

np.int64(40)

In [ ]:
s.iloc[[1,2,4]]

1    20
2    30
4    50
Name: calories, dtype: int64

In [ ]:
s.iloc[2:4]

2    30
3    40
Name: calories, dtype: int64

In [ ]:
index = ["apple", "banana", "grapes", "orange", "strawberry"]
s.index = index
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

In [ ]:
#loc -> label based indexing
s.loc['grapes']

np.int64(30)

In [ ]:
s.loc[['grapes', 'orange', 'apple']]

grapes    30
orange    40
apple     10
Name: calories, dtype: int64

In [ ]:
s.loc['banana' : 'orange'] # starting and stopping will be the included

banana    20
grapes    30
orange    40
Name: calories, dtype: int64

In [ ]:
#Series using dictionaries
fruit_protein = {
    "Avacado" : 2.0,
    "Guava" : 2.6,
    "Blackberries" : 2.0,
    "Oranges" : 0.9,
    "Banana" : 1.1,
    "Apples" : 0.3,
    "Kiwi" : 1.1,
    "Pomegranate" : 1.7,
    "Mango" : 0.8,
    "Cherries" : 1.0
}

In [ ]:
s2 = pd.Series(fruit_protein, name = "protein")
s2

Avacado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: protein, dtype: float64

In [ ]:
s2.keys()

Index(['Avacado', 'Guava', 'Blackberries', 'Oranges', 'Banana', 'Apples',
       'Kiwi', 'Pomegranate', 'Mango', 'Cherries'],
      dtype='object')

In [ ]:
fruit_protein.values()

dict_values([2.0, 2.6, 2.0, 0.9, 1.1, 0.3, 1.1, 1.7, 0.8, 1.0])

In [ ]:
s2[0:6]

Avacado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Name: protein, dtype: float64

In [ ]:
s2.iloc[5]

np.float64(0.3)

In [ ]:
s2.iloc[2: 7]

Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Name: protein, dtype: float64

In [ ]:
s2.iloc[[1, 4, 5, 7]]

Guava          2.6
Banana         1.1
Apples         0.3
Pomegranate    1.7
Name: protein, dtype: float64

In [ ]:
s2.loc['Banana']

np.float64(1.1)

In [ ]:
s2.loc[['Banana', 'Apples', "Kiwi"]]

Banana    1.1
Apples    0.3
Kiwi      1.1
Name: protein, dtype: float64

In [ ]:
#Conditional selection
s2>1

Avacado          True
Guava            True
Blackberries     True
Oranges         False
Banana           True
Apples          False
Kiwi             True
Pomegranate      True
Mango           False
Cherries        False
Name: protein, dtype: bool

In [ ]:
s2[s2 > 1]

Avacado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Name: protein, dtype: float64

In [ ]:
#logical operations and, or, not
[(s2 > 0.5) & (s2 < 1)]

[Avacado         False
 Guava           False
 Blackberries    False
 Oranges          True
 Banana          False
 Apples          False
 Kiwi            False
 Pomegranate     False
 Mango            True
 Cherries        False
 Name: protein, dtype: bool]

In [ ]:
s2[(s2 > 0.5) & (s2 < 1)]

Oranges    0.9
Mango      0.8
Name: protein, dtype: float64

In [ ]:
s2[(s2 > 0.5) | (s2 < 1)]

Avacado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: protein, dtype: float64

In [ ]:
s2[~(s2 > 1)]

Oranges     0.9
Apples      0.3
Mango       0.8
Cherries    1.0
Name: protein, dtype: float64

In [ ]:
#Modifying the values
s2["Mango"] = 2.8
s2

Avacado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           2.8
Cherries        1.0
Name: protein, dtype: float64

In [ ]:
#todo
import numpy as np

In [ ]:
ser = pd.Series(['a', np.nan, 1, np.nan, 2])
ser.notnull().sum()

np.int64(3)

In [ ]:
#dataframes
data = {
    "Name" : ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age" : [25, 30, 35, np.nan, 29, 25],
    "Department" : ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary" : [50000, 60000, 70000, 62000, np.nan, 50000]
}
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [ ]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [ ]:
#printing the starting values
df.head(2)

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [ ]:
#prints default 5 values
df.tail()

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [ ]:
#prints last 3 values
df.tail(3)

    Name   Age Department   Salary
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [ ]:
#loc and iloc
df.loc[1: 3] #lable based indexing includes starting and ending indices

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0

In [ ]:
df.iloc[1 :3]

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0

In [ ]:
df.loc[1 : 3, ["Age", "Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance
3   NaN         IT

In [ ]:
df.iloc[1:3, :2]

      Name   Age
1      Bob  30.0
2  Charlie  35.0

In [ ]:
df["Age"]

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df[["Age", "Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [ ]:
df.drop("Age", axis = 1) # removing "age" col

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [ ]:
df #age is not deleted from the original dataframe

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [ ]:
df.drop("Age", axis = 1, inplace = True) #since this code is run multiple times , and ae is no longer existed in the dataframe , we are getting error

KeyError: "['Age'] not found in axis"

In [ ]:
df

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [ ]:
df.shape

(6, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Department  6 non-null      object
 2   Salary      5 non-null      float64
dtypes: float64(1), object(2)
memory usage: 276.0+ bytes

In [ ]:
df.describe()

             Salary
count      5.000000
mean   58400.000000
std     8532.291603
min    50000.000000
25%    50000.000000
50%    60000.000000
75%    62000.000000
max    70000.000000

In [ ]:
#broadcasting
df["Salary"] = df["Salary"] + 5000
df["Salary"]

0    65000.0
1    75000.0
2    85000.0
3    77000.0
4        NaN
5    65000.0
Name: Salary, dtype: float64

In [ ]:
df.rename(columns = {"Department" : "Dept"}, inplace = True)
df

      Name     Dept   Salary
0    Alice       HR  65000.0
1      Bob       IT  75000.0
2  Charlie  Finance  85000.0
3    David       IT  77000.0
4      Eve       HR      NaN
5    Alice       HR  65000.0

In [ ]:
#printing unique values of particular col
df["Salary"].unique()

array([65000., 75000., 85000., 77000.,    nan])

In [ ]:
df["Dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [ ]:
#count of employees working in each department
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [ ]:
df["Promoted Salary"] = df["Salary"] * 10

In [ ]:
df

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  65000.0         650000.0
1      Bob       IT  75000.0         750000.0
2  Charlie  Finance  85000.0         850000.0
3    David       IT  77000.0         770000.0
4      Eve       HR      NaN              NaN
5    Alice       HR  65000.0         650000.0

In [ ]:
#data cleaning
#step 1 : check number of null values
df.isnull().sum()

Name               0
Dept               0
Salary             1
Promoted Salary    1
dtype: int64

In [ ]:
df.dropna() #removes all the rows with null values, does not affect the original dataframe as we have not did inplace = True

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  65000.0         650000.0
1      Bob       IT  75000.0         750000.0
2  Charlie  Finance  85000.0         850000.0
3    David       IT  77000.0         770000.0
5    Alice       HR  65000.0         650000.0

In [ ]:
df

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  65000.0         650000.0
1      Bob       IT  75000.0         750000.0
2  Charlie  Finance  85000.0         850000.0
3    David       IT  77000.0         770000.0
4      Eve       HR      NaN              NaN
5    Alice       HR  65000.0         650000.0

In [ ]:
df.dropna(how = "any") #if any row that had null value

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  65000.0         650000.0
1      Bob       IT  75000.0         750000.0
2  Charlie  Finance  85000.0         850000.0
3    David       IT  77000.0         770000.0
5    Alice       HR  65000.0         650000.0

In [ ]:
df.dropna(how = "all") # if all the values in the row had null values then drop that row

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  65000.0         650000.0
1      Bob       IT  75000.0         750000.0
2  Charlie  Finance  85000.0         850000.0
3    David       IT  77000.0         770000.0
4      Eve       HR      NaN              NaN
5    Alice       HR  65000.0         650000.0

In [ ]:
df

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  65000.0         650000.0
1      Bob       IT  75000.0         750000.0
2  Charlie  Finance  85000.0         850000.0
3    David       IT  77000.0         770000.0
4      Eve       HR      NaN              NaN
5    Alice       HR  65000.0         650000.0

In [ ]:
df.fillna(0)

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  65000.0         650000.0
1      Bob       IT  75000.0         750000.0
2  Charlie  Finance  85000.0         850000.0
3    David       IT  77000.0         770000.0
4      Eve       HR      0.0              0.0
5    Alice       HR  65000.0         650000.0

In [ ]:
df["Salary"].fillna(df["Salary"].median()) #we have filled the null value with median in the salary column

0    65000.0
1    75000.0
2    85000.0
3    77000.0
4    75000.0
5    65000.0
Name: Salary, dtype: float64

In [ ]:
df # here I have run the dataframe creation cell() to get the age column back and ran "df" in the current cell

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [ ]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
#forward fill
df["Age"].fillna(method = "ffill") # replaces the missing value with the value above to it

/tmp/ipykernel_10158/544980945.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "ffill")

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
#backward fill
df["Age"].fillna(method = "bfill") # replaces the missing value with the value above to it

/tmp/ipykernel_10158/3026805218.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "bfill")

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df["Name"] = df["Name"].replace("Charlie", "Rose")
df

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0
2   Rose  35.0    Finance  70000.0
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [ ]:
#Duplicates
df_dup = df[df.duplicated()]
df_dup

    Name   Age Department   Salary
5  Alice  25.0         HR  50000.0

In [ ]:
df_dup = df[df.duplicated(keep = "first")] #"it keeps first element and marks the one that is duplicated"
df_dup

    Name   Age Department   Salary
5  Alice  25.0         HR  50000.0

In [ ]:
df_dup = df[df.duplicated(keep = "last")] #"it keeps last element and marks the one that is duplicated"
df_dup

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0

In [ ]:
df = df.drop_duplicates()
df

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0
2   Rose  35.0    Finance  70000.0
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN

In [ ]:
#invalid data
#lambda
df["Promoted Salary"] = df["Salary"] * 10
df

    Name   Age Department   Salary  Promoted Salary
0  Alice  25.0         HR  50000.0         500000.0
1    Bob  30.0         IT  60000.0         600000.0
2   Rose  35.0    Finance  70000.0         700000.0
3  David   NaN         IT  62000.0         620000.0
4    Eve  29.0         HR      NaN              NaN

In [ ]:
#invalid data
#lambda
df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x > 650000 else x)
df

    Name   Age Department   Salary  Promoted Salary
0  Alice  25.0         HR  50000.0          50000.0
1    Bob  30.0         IT  60000.0          60000.0
2   Rose  35.0    Finance  70000.0           7000.0
3  David   NaN         IT  62000.0          62000.0
4    Eve  29.0         HR      NaN              NaN