<a href="https://colab.research.google.com/github/Lalasa-web/Gen-AI-with-prompt-engineering-/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
s = pd.Series([10, 20, 30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
s.name = "calories"
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [6]:
s.dtype

dtype('int64')

In [7]:
s.index #start = include, end = exclude, step = values to jump

RangeIndex(start=0, stop=5, step=1)

In [8]:
#indexing
s[0]

np.int64(10)

In [9]:
s[0:2]

0    10
1    20
Name: calories, dtype: int64

In [10]:
#iloc -> location based indexing (starting : included, stopping : excluded)
s.iloc[3]

np.int64(40)

In [11]:
s.iloc[[1,2,4]]

1    20
2    30
4    50
Name: calories, dtype: int64

In [12]:
s.iloc[2:4]

2    30
3    40
Name: calories, dtype: int64

In [13]:
index = ["apple", "banana", "grapes", "orange", "strawberry"]
s.index = index
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

In [14]:
#loc -> label based indexing
s.loc['grapes']

np.int64(30)

In [15]:
s.loc[['grapes', 'orange', 'apple']]

grapes    30
orange    40
apple     10
Name: calories, dtype: int64

In [16]:

s.loc['banana' : 'orange'] # starting and stopping will be the included

banana    20
grapes    30
orange    40
Name: calories, dtype: int64

In [17]:
#Series using dictionaries
fruit_protein = {
    "Avacado" : 2.0,
    "Guava" : 2.6,
    "Blackberries" : 2.0,
    "Oranges" : 0.9,
    "Banana" : 1.1,
    "Apples" : 0.3,
    "Kiwi" : 1.1,
    "Pomegranate" : 1.7,
    "Mango" : 0.8,
    "Cherries" : 1.0
}

In [18]:
s2 = pd.Series(fruit_protein, name = "protein")
s2

Avacado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: protein, dtype: float64

In [19]:
s2.keys()

Index(['Avacado', 'Guava', 'Blackberries', 'Oranges', 'Banana', 'Apples',
       'Kiwi', 'Pomegranate', 'Mango', 'Cherries'],
      dtype='object')

In [20]:
fruit_protein.values()

dict_values([2.0, 2.6, 2.0, 0.9, 1.1, 0.3, 1.1, 1.7, 0.8, 1.0])

In [21]:
s2[0:6]

Avacado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Name: protein, dtype: float64

In [22]:
s2.iloc[5]

np.float64(0.3)

In [23]:
s2.iloc[2: 7]

Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Name: protein, dtype: float64

In [24]:
s2.iloc[[1, 4, 5, 7]]

Guava          2.6
Banana         1.1
Apples         0.3
Pomegranate    1.7
Name: protein, dtype: float64

In [25]:
s2.loc['Banana']

np.float64(1.1)

In [26]:
s2.loc[['Banana', 'Apples', "Kiwi"]]

Banana    1.1
Apples    0.3
Kiwi      1.1
Name: protein, dtype: float64

In [27]:
#Conditional selection
s2>1

Avacado          True
Guava            True
Blackberries     True
Oranges         False
Banana           True
Apples          False
Kiwi             True
Pomegranate      True
Mango           False
Cherries        False
Name: protein, dtype: bool

In [28]:
s2[s2 > 1]

Avacado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Name: protein, dtype: float64

In [29]:
#logical operations and, or, not
[(s2 > 0.5) & (s2 < 1)]

[Avacado         False
 Guava           False
 Blackberries    False
 Oranges          True
 Banana          False
 Apples          False
 Kiwi            False
 Pomegranate     False
 Mango            True
 Cherries        False
 Name: protein, dtype: bool]

In [30]:
s2[(s2 > 0.5) & (s2 < 1)]

Oranges    0.9
Mango      0.8
Name: protein, dtype: float64

In [31]:
s2[(s2 > 0.5) | (s2 < 1)]

Avacado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: protein, dtype: float64

In [32]:
s2[~(s2 > 1)]

Oranges     0.9
Apples      0.3
Mango       0.8
Cherries    1.0
Name: protein, dtype: float64

In [33]:
#Modifying the values
s2["Mango"] = 2.8
s2

Avacado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           2.8
Cherries        1.0
Name: protein, dtype: float64

In [34]:
#todo
import numpy as np

In [35]:
ser = pd.Series(['a', np.nan, 1, np.nan, 2])
ser.notnull().sum()

np.int64(3)

In [36]:
#dataframes
data = {
    "Name" : ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age" : [25, 30, 35, np.nan, 29, 25],
    "Department" : ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary" : [50000, 60000, 70000, 62000, np.nan, 50000]
}
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [37]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [38]:
#printing the starting values
df.head(2)

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [39]:
#prints default 5 values
df.tail()

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [40]:
#prints last 3 values
df.tail(3)

    Name   Age Department   Salary
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [42]:
#loc and iloc
df.loc[1: 3] #lable based indexing includes starting and ending indices

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0

In [43]:
df.iloc[1 :3]

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0

In [44]:
df.loc[1 : 3, ["Age", "Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance
3   NaN         IT

In [45]:
df.iloc[1:3, :2]

      Name   Age
1      Bob  30.0
2  Charlie  35.0

In [46]:
df["Age"]

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64

In [47]:
df[["Age", "Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [48]:
df.drop("Age", axis = 1) # removing "age" col

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [49]:
df #age is not deleted from the original dataframe

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [50]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [51]:
df.shape

(6, 4)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [53]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [54]:
#broadcasting
df["Salary"] = df["Salary"] + 5000
df["Salary"]

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [55]:
df.rename(columns = {"Department" : "Dept"}, inplace = True)
df

      Name   Age     Dept   Salary
0    Alice  25.0       HR  55000.0
1      Bob  30.0       IT  65000.0
2  Charlie  35.0  Finance  75000.0
3    David   NaN       IT  67000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  55000.0

In [56]:
#printing unique values of particular col
df["Salary"].unique()

array([55000., 65000., 75000., 67000.,    nan])

In [57]:
df["Dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [58]:
#count of employees working in each department
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [59]:
df["Promoted Salary"] = df["Salary"] * 10

In [60]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [61]:
#data cleaning
#step 1 : check number of null values
df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted Salary    1
dtype: int64

In [62]:
df.dropna() #removes all the rows with null values, does not affect the original dataframe as we have not did inplace = True

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
5    Alice  25.0       HR  55000.0         550000.0

In [63]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [64]:
df.dropna(how = "any") #if any row that had null value

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
5    Alice  25.0       HR  55000.0         550000.0

In [65]:
df.dropna(how = "all") # if all the values in the row had null values then drop that row

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [66]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [67]:
df.fillna(0)

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   0.0       IT  67000.0         670000.0
4      Eve  29.0       HR      0.0              0.0
5    Alice  25.0       HR  55000.0         550000.0

In [70]:
df["Age"].fillna(df["Age"].mean()) #we have filled the null value with mean in the age column

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [68]:
df["Salary"].fillna(df["Salary"].median()) #we have filled the null value with median in the salary column

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    65000.0
5    55000.0
Name: Salary, dtype: float64

In [71]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [72]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [73]:
#forward fill
df["Age"].fillna(method = "ffill") # replaces the missing value with the value above to it

/tmp/ipykernel_14382/66425444.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "ffill") # replaces the missing value with the value above to it

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [74]:
#backward fill
df["Age"].fillna(method = "bfill") # replaces the missing value with the value above to it

/tmp/ipykernel_14382/3521509880.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "bfill") # replaces the missing value with the value above to it

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [75]:
df["Name"] = df["Name"].replace("Charlie", "Rose")
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0         750000.0
3  David   NaN       IT  67000.0         670000.0
4    Eve  29.0       HR      NaN              NaN
5  Alice  25.0       HR  55000.0         550000.0

In [76]:
#Duplicates
df_dup = df[df.duplicated()]
df_dup

    Name   Age Dept   Salary  Promoted Salary
5  Alice  25.0   HR  55000.0         550000.0

In [77]:
df_dup = df[df.duplicated(keep = "first")] #"it keeps first element and marks the one that is duplicated"
df_dup

    Name   Age Dept   Salary  Promoted Salary
5  Alice  25.0   HR  55000.0         550000.0

In [78]:
df_dup = df[df.duplicated(keep = "last")] #"it keeps last element and marks the one that is duplicated"
df_dup

    Name   Age Dept   Salary  Promoted Salary
0  Alice  25.0   HR  55000.0         550000.0

In [79]:
df = df.drop_duplicates()
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0         750000.0
3  David   NaN       IT  67000.0         670000.0
4    Eve  29.0       HR      NaN              NaN

In [80]:
#invalid data
#lambda
df["Promoted Salary"] = df["Salary"] * 10
df

/tmp/ipykernel_14382/1684632829.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Promoted Salary"] = df["Salary"] * 10

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0         750000.0
3  David   NaN       IT  67000.0         670000.0
4    Eve  29.0       HR      NaN              NaN

In [81]:
#invalid data
#lambda
df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x > 650000 else x)
df

/tmp/ipykernel_14382/627835870.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x > 650000 else x)

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0          75000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  29.0       HR      NaN              NaN

In [82]:
#apply and lamda
#without using lambda
def multiplying_age(x):
  return x * 2

df["Age"] = df["Age"].apply(multiplying_age)

/tmp/ipykernel_14382/2917812229.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(multiplying_age)

In [83]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  50.0       HR  55000.0         550000.0
1    Bob  60.0       IT  65000.0         650000.0
2   Rose  70.0  Finance  75000.0          75000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  58.0       HR      NaN              NaN

In [86]:
df["Age"] = df["Age"].apply(lambda x:x/2) #with lambda usage

/tmp/ipykernel_14382/861308642.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(lambda x:x/2) #with lambda usage

In [85]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0          75000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  29.0       HR      NaN              NaN

In [87]:
#joins and merges
department_info = {
    "Dept" : ["HR", "IT", "Finance"],
    "Location" : ["New York", "San Francisco", "Chicago"],
    "Manager" : ["Laura", "Steve", "Naina"]
}

df2 = pd.DataFrame(department_info)

In [88]:
df2

      Dept       Location Manager
0       HR       New York   Laura
1       IT  San Francisco   Steve
2  Finance        Chicago   Naina

In [89]:
#concat
pd.concat([df, df2]) #the two datasets have been stacked horizanally

    Name   Age     Dept   Salary  Promoted Salary       Location Manager
0  Alice  12.5       HR  55000.0         550000.0            NaN     NaN
1    Bob  15.0       IT  65000.0         650000.0            NaN     NaN
2   Rose  17.5  Finance  75000.0          75000.0            NaN     NaN
3  David   NaN       IT  67000.0          67000.0            NaN     NaN
4    Eve  14.5       HR      NaN              NaN            NaN     NaN
0    NaN   NaN       HR      NaN              NaN       New York   Laura
1    NaN   NaN       IT      NaN              NaN  San Francisco   Steve
2    NaN   NaN  Finance      NaN              NaN        Chicago   Naina

In [90]:
pd.concat([df, df2], axis = 1) #the two datasets have been stacked vertically

,Name,Age,Dept,Salary,Promoted Salary,Dept,Location,Manager
0,Alice,12.5,HR,55000.0,550000.0,HR,New York,Laura
1,Bob,15.0,IT,65000.0,650000.0,IT,San Francisco,Steve
2,Rose,17.5,Finance,75000.0,75000.0,Finance,Chicago,Naina
3,David,NaN,IT,67000.0,67000.0,NaN,NaN,NaN
4,Eve,14.5,HR,NaN,NaN,NaN,NaN,NaN

In [91]:
# we merge the two datasets to not to have the same column repeated
pd.merge(df, df2, on = "Dept")

    Name   Age     Dept   Salary  Promoted Salary       Location Manager
0  Alice  12.5       HR  55000.0         550000.0       New York   Laura
1    Bob  15.0       IT  65000.0         650000.0  San Francisco   Steve
2   Rose  17.5  Finance  75000.0          75000.0        Chicago   Naina
3  David   NaN       IT  67000.0          67000.0  San Francisco   Steve
4    Eve  14.5       HR      NaN              NaN       New York   Laura

In [93]:
data1 = pd.read_csv("/content/sample_data/california_housing_test.csv")
data1.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [96]:
data1.shape

(3000, 9)

In [98]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

In [99]:
df2.columns

Index(['Dept', 'Location', 'Manager'], dtype='object')

In [102]:
df["Age"].sort_values()

0    12.5
4    14.5
1    15.0
2    17.5
3     NaN
Name: Age, dtype: float64

In [104]:
df["Age"].sort_values(ascending = False) #prints in descending order

2    17.5
1    15.0
4    14.5
0    12.5
3     NaN
Name: Age, dtype: float64

In [111]:
df.groupby("Salary")["Age"].max()

Salary
55000.0    12.5
65000.0    15.0
67000.0     NaN
75000.0    17.5
Name: Age, dtype: float64

In [112]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  12.5       HR  55000.0         550000.0
1    Bob  15.0       IT  65000.0         650000.0
2   Rose  17.5  Finance  75000.0          75000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  14.5       HR      NaN              NaN

In [115]:
data3 = {
    "Name" : ["Lalasa", "Lasya", "Pavan", "Sai", "Gagana"],
    "Age" : [20, 21, 22, 23, 24],
    "Salary" : [100000, 200000, 300000, 400000, 100000],
    "City" : ["Chennai", "Bengluru", "America", "Hyderabad", "Chennai"]
}
df3 = pd.DataFrame(data3)

In [116]:
df3

     Name  Age  Salary       City
0  Lalasa   20  100000    Chennai
1   Lasya   21  200000   Bengluru
2   Pavan   22  300000    America
3     Sai   23  400000  Hyderabad
4  Gagana   24  100000    Chennai

In [118]:
df3.groupby('City').agg({"Salary" : "mean", "Age" : "max"})

             Salary  Age
City
America    300000.0   22
Bengluru   200000.0   21
Chennai    100000.0   24
Hyderabad  400000.0   23

In [120]:
df3.to_csv("pandas", index = True) #converting this file into csv file, we can check it through navigating files in the colab